Repository geeksforsocialchange/PlaceCal, pull requests merged in 2022-04, with the labels that each got.

#1109 Safely read opening_times from partner
  app/graphql/types/partner_type.rb
  test/integration/graphql/partners_integration_test.rb
Labels: bug

#1115 Fixed bug in ICS event download action
  app/models/event.rb
  test/models/events_test.rb
Labels: bug, patch

#1112 Articles now have Image Headers
  app/controllers/admin/articles_controller.rb
  app/controllers/admin/partners_controller.rb
  app/graphql/types/article_type.rb
  app/models/article.rb
  app/policies/article_policy.rb
  app/uploaders/article_image_uploader.rb
  app/views/admin/articles/_form.html.erb
  db/migrate/20220405102801_add_article_header_to_articles.rb
  db/schema.rb
  test/integration/admin/sites_integration_test.rb
  test/integration/graphql/article_query_type_test.rb
  test/integration/graphql/partners_integration_test.rb
  test/test_helper.rb
Labels: enhancement

#1123 Partner admin interface site duplicates
  app/helpers/partners_helper.rb
  app/models/partner.rb
  app/models/site.rb
  app/views/admin/partners/_service_area_fields.html.erb
  app/views/admin/partners/edit.html.erb
  test/controllers/admin/partner_edit_site_test.rb
  test/integration/admin/partner_integration_test.rb
Labels: bug, patch

#1125 Articles can have tags (part one!)
  app/models/article.rb
  app/models/article_tag.rb
  app/models/tag.rb
  app/policies/article_policy.rb
  app/views/admin/articles/_form.html.erb
  db/migrate/20220406135448_create_article_tags.rb
  db/schema.rb
  test/controllers/admin/articles_controller_test.rb
  test/integration/graphql/event_integration_test.rb
Labels: enhancement

#1131 Filter articles by tagID graphql endpoint
  app/graphql/types/query_type.rb
  app/models/article.rb
  test/integration/graphql/article_by_tag_query_test.rb
  test/integration/graphql/articles_by_partner_tag_test.rb
  test/models/article_test.rb
Labels: enhancement

#1133 Title on admin edit article page
  app/views/admin/articles/edit.html.erb
Labels: bug

#1134 Make login and password reset processes nicer
  app/assets/stylesheets/home/_form.sass
  app/controllers/application_controller.rb
  app/controllers/sessions_controller.rb
  app/controllers/users/auth_common.rb
  app/controllers/users/confirmations_controller.rb
  app/controllers/users/invitations_controller.rb
  app/controllers/users/passwords_controller.rb
  app/controllers/users/sessions_controller.rb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/layouts/application.html.erb
  config/routes.rb
  test/integration/users_log_in_go_to_admin_site_test.rb
  test/integration/users_login_on_site_test.rb
Labels: enhancement

#1136 Be more explicit about loading dependencies
  app/controllers/users/confirmations_controller.rb
  app/controllers/users/invitations_controller.rb
  app/controllers/users/passwords_controller.rb
  app/controllers/users/sessions_controller.rb
Labels: bug, patch

#1141 Skip updated_at touch on calendar import
  app/models/calendar.rb
  test/fixtures/vcr_cassettes/import_test_calendar.yml
  test/system/events_import_test.rb
  test/test_helper.rb
Labels: bug

#1139 Upgrade to Rails 7
  .env.example
  .github/workflows/test.yml
  .ruby-version
  Gemfile
  Gemfile.lock
  app/models/ical.rb
  babel.config.js
  config/application.rb
  config/environments/test.rb
  config/initializers/content_security_policy.rb
  config/initializers/filter_parameter_logging.rb
  config/initializers/inflections.rb
  config/initializers/new_framework_defaults_7_0.rb
  config/initializers/permissions_policy.rb
  db/schema.rb
  test/test_helper.rb
  yarn.lock
Labels: chore

#1142 Update Uglifier config
  config/environments/staging.rb
Labels: bug

#1143 Replace Uglifier with Terser
  Gemfile
  Gemfile.lock
  config/environments/production.rb
  config/environments/staging.rb
Labels: bug

#1144 Update yarn command
  .github/workflows/test.yml
Labels: bug

#1145 Upgrade yarn
  .github/workflows/test.yml
  package.json
  yarn.lock
Labels: chore

#1146 Update CI actions
  .github/workflows/test.yml
Labels: chore

#1152 Revert to Rails 6
  .env.example
  .github/workflows/test.yml
  .ruby-version
  Gemfile
  Gemfile.lock
  app/models/ical.rb
  babel.config.js
  bin/setup
  config/application.rb
  config/environments/production.rb
  config/environments/staging.rb
  config/environments/test.rb
  config/initializers/content_security_policy.rb
  config/initializers/filter_parameter_logging.rb
  config/initializers/inflections.rb
  config/initializers/new_framework_defaults_7_0.rb
  config/initializers/permissions_policy.rb
  db/schema.rb
  package.json
  test/test_helper.rb
  yarn.lock
Labels: chore

#1138 Upgrade dependancies
  .env.example
  .github/workflows/test.yml
  .nvmrc
  .ruby-version
  Gemfile
  Gemfile.lock
  app/models/ical.rb
  package.json
  test/test_helper.rb
  yarn.lock
Labels: chore

#1154 Change yarn and node version
  package.json
Labels: chore

#1155 Update babel config
  babel.config.js
Labels: chore

#1156 Fix node version
  package.json
Labels: bug, patch, chore

#1147 Meetup.com calendar import source
  app/models/calendar.rb
  app/models/calendar_parser.rb
  app/models/events/meetup_event.rb
  app/models/parsers/meetup.rb
Labels: enhancement

#1162 Migrate to jsbundling
  .github/workflows/test.yml
  .gitignore
  Gemfile
  Gemfile.lock
  Procfile.dev
  README.md
  app/assets/builds/.keep
  app/assets/config/manifest.js
  app/components/admin_index/_admin_index.html.erb
  app/components/navigation/_navigation.html.erb
  app/components/paginator/_paginator.html.erb
  app/javascript/admin.js
  app/javascript/application.js
  app/javascript/packs/admin.js
  app/javascript/src/calendar-form.js
  app/javascript/src/components/breadcrumb.js
  app/javascript/src/components/navigation.js
  app/javascript/src/components/paginator.js
  app/javascript/src/datatable.js
  app/javascript/src/jquery.js
  app/javascript/src/opening-times.js
  app/javascript/src/reveal.js
  app/javascript/src/ward-picker.js
  app/views/admin/pages/home.html.erb
  app/views/layouts/admin/_datatable.html.erb
  app/views/layouts/admin/application.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/mountain_view.html.erb
  bin/dev
  bin/webpack
  bin/webpack-dev-server
  config/application.rb
  config/cable.yml
  config/environments/development.rb
  config/webpack/development.js
  config/webpack/environment.js
  config/webpack/production.js
  config/webpack/staging.js
  config/webpack/test.js
  config/webpacker.yml
  esbuild.config.js
  package.json
  postcss.config.js
  yarn.lock
Labels: minor, javascript, chore

#1163 Fix Uglifier issue during deploy
  config/environments/production.rb
  config/environments/staging.rb
Labels: bug, patch

#1164 Comment out js compression to fix deploy
  Gemfile
  Gemfile.lock
  config/environments/production.rb
  config/environments/staging.rb
Labels: bug, patch

#1168 Add GeoCoordinates to Partner (GraphQL)
  app/graphql/types/address_type.rb
  app/graphql/types/geo_coordinates_type.rb
  app/graphql/types/opening_hours_type.rb
  app/graphql/types/partner_type.rb
  test/integration/graphql/partners_integration_test.rb
  test/test_helper.rb
Labels: enhancement

#1171 Add HTTP 422 to render errors
  app/controllers/admin/articles_controller.rb
  app/controllers/admin/calendars_controller.rb
  app/controllers/admin/collections_controller.rb
  app/controllers/admin/neighbourhoods_controller.rb
  app/controllers/admin/omniauth_callbacks_controller.rb
  app/controllers/admin/partners_controller.rb
  app/controllers/admin/sites_controller.rb
  app/controllers/admin/supporters_controller.rb
  app/controllers/admin/tags_controller.rb
  app/controllers/admin/users_controller.rb
Labels: bug

#1173 Move GeoCoordinates type into AddressType
  app/graphql/types/address_type.rb
  app/graphql/types/partner_type.rb
  app/models/address.rb
  test/integration/graphql/event_integration_test.rb
  test/integration/graphql/partners_integration_test.rb
Labels: bug

#1175 Refactor calendar importer
  app/jobs/calendar_importer/calendar_importer.rb
  app/jobs/calendar_importer/calendar_importer_task.rb
  app/jobs/calendar_importer/event_resolver.rb
  app/jobs/calendar_importer/events/base.rb
  app/jobs/calendar_importer/events/eventbrite_event.rb
  app/jobs/calendar_importer/events/facebook_event.rb
  app/jobs/calendar_importer/events/ics_event.rb
  app/jobs/calendar_importer/events/manchester_uni_event.rb
  app/jobs/calendar_importer/events/meetup_event.rb
  app/jobs/calendar_importer/events/zarts_event.rb
  app/jobs/calendar_importer/parsers/base.rb
  app/jobs/calendar_importer/parsers/eventbrite.rb
  app/jobs/calendar_importer/parsers/facebook.rb
  app/jobs/calendar_importer/parsers/ics.rb
  app/jobs/calendar_importer/parsers/manchester_uni.rb
  app/jobs/calendar_importer/parsers/meetup.rb
  app/jobs/calendar_importer/parsers/xml.rb
  app/jobs/calendar_importer/parsers/zarts.rb
  app/jobs/calendar_importer_job.rb
  app/models/address.rb
  app/models/calendar.rb
  app/models/partner.rb
  lib/tasks/events.rake
  test/jobs/calendar_importer/calendar_importer_test.rb
  test/jobs/calendar_importer/events_import_test.rb
Labels: enhancement

#1179 Events with no locations are valid now
  app/jobs/calendar_importer/calendar_importer_task.rb
Labels: enhancement

#1178 Meetup.com events without an end time don't break the importer
  app/jobs/calendar_importer/events/meetup_event.rb
Labels: bug

#1181 Fixup datatables on Calendar page
  app/datatables/calendar_datatable.rb
  app/views/admin/calendars/index.html.erb
Labels: enhancement

#1180 Admin calendar url hints
  app/helpers/calendars_helper.rb
  app/jobs/calendar_importer/calendar_importer.rb
  app/jobs/calendar_importer/events/ticketsolve_event.rb
  app/jobs/calendar_importer/parsers/base.rb
  app/jobs/calendar_importer/parsers/eventbrite.rb
  app/jobs/calendar_importer/parsers/facebook.rb
  app/jobs/calendar_importer/parsers/ics.rb
  app/jobs/calendar_importer/parsers/manchester_uni.rb
  app/jobs/calendar_importer/parsers/meetup.rb
  app/jobs/calendar_importer/parsers/ticketsolve.rb
  app/views/admin/calendars/_form.html.erb
Labels: enhancement

#1184 Add notice_count to fix Calendar render bug
  app/datatables/calendar_datatable.rb
  app/models/calendar.rb
  app/views/admin/calendars/index.html.erb
  db/migrate/20220427131452_add_notices_count_to_calendar.rb
  db/schema.rb
Labels: bug, patch

#1187 1012: Make calendars work
  app/helpers/calendars_helper.rb
  app/jobs/calendar_importer/event_resolver.rb
  app/jobs/calendar_importer/parsers/base.rb
  app/jobs/calendar_importer/parsers/ics.rb
  app/jobs/calendar_importer_job.rb
  app/models/parsers/base.rb
  app/models/parsers/eventbrite.rb
  app/models/parsers/facebook.rb
  app/models/parsers/ics.rb
  app/models/parsers/manchester_uni.rb
  app/models/parsers/meetup.rb
  app/models/parsers/xml.rb
  app/models/parsers/zarts.rb
  lib/tasks/events.rake
Labels: bug

#1190 Fix various calendar bugs
  app/helpers/calendars_helper.rb
  app/jobs/calendar_importer/event_resolver.rb
  app/jobs/calendar_importer/parsers/base.rb
  app/jobs/calendar_importer/parsers/ics.rb
  app/jobs/calendar_importer_job.rb
  app/models/parsers/base.rb
  app/models/parsers/eventbrite.rb
  app/models/parsers/facebook.rb
  app/models/parsers/ics.rb
  app/models/parsers/manchester_uni.rb
  app/models/parsers/meetup.rb
  app/models/parsers/xml.rb
  app/models/parsers/zarts.rb
  lib/tasks/events.rake
Labels: bug, patch

#1193 View events inside the admin interface
  app/controllers/admin/calendars_controller.rb
  app/models/event.rb
  app/views/admin/calendars/_form.html.erb
  app/views/admin/calendars/show.html.erb
Labels: enhancement

#1195 Partners with service areas don't show up on the map
  app/components/map/_map.html.erb
  app/controllers/application_controller.rb
Labels: bug
