Repository geeksforsocialchange/PlaceCal, pull requests merged in 2022-03, with the labels that each got.

#1001 Update copyright message, add bug report and build links to admin
  app/components/footer/_footer.html.erb
  app/views/layouts/admin/_admin_navigation.html.erb
Labels: patch, enhancement

#1006 Site lookup Partners now includes service areas
  app/models/partner.rb
  test/fixtures/neighbourhoods.yml
  test/models/partner_test.rb
  test/test_helper.rb
Labels: patch, enhancement

#1008 Bypass rails authentication for graphql endpoint
  app/controllers/graphql_controller.rb
Labels: security, enhancement

#1010 Fix calendar organiser preselect bug
  app/controllers/admin/calendars_controller.rb
  test/integration/admin/calendars_integration_test.rb
Labels: bug, patch

#1016 Finding events via service areas
  app/models/event.rb
  test/integration/event_site_integration_test.rb
  test/models/event_test.rb
Labels: patch, enhancement

#1021 Root users can assign service areas at will
  app/models/partner.rb
  test/models/partner_test.rb
Labels: bug, patch

#1024 Fix rollbar logging
  config/initializers/rollbar.rb
Labels: bug, vv, e, patch

#1025 Add updated_at column to index pages / datatables
  app/controllers/admin/articles_controller.rb
  app/controllers/admin/calendars_controller.rb
  app/controllers/admin/partners_controller.rb
  app/controllers/admin/sites_controller.rb
  app/controllers/admin/tags_controller.rb
  app/controllers/admin/users_controller.rb
  app/datatables/article_datatable.rb
  app/datatables/calendar_datatable.rb
  app/datatables/partner_datatable.rb
  app/datatables/site_datatable.rb
  app/datatables/tag_datatable.rb
  app/datatables/user_datatable.rb
  app/views/admin/articles/index.html.erb
  app/views/admin/calendars/index.html.erb
  app/views/admin/neighbourhoods/index.html.erb
  app/views/admin/partners/index.html.erb
  app/views/admin/sites/index.html.erb
  app/views/admin/tags/index.html.erb
  app/views/admin/users/index.html.erb
Labels: enhancement

#1031 Fix admin user form
  app/views/admin/users/new.html.erb
  test/integration/admin/user_integration_test.rb
Labels: bug, patch

#1036 GraphQL Partner public contact info data fields
  app/graphql/types/partner_type.rb
  test/integration/graphql/partners_integration_test.rb
Labels: enhancement

#1038 API pagination
  app/graphql/place_cal_schema.rb
  app/graphql/types/query_type.rb
  test/integration/graphql/event_integration_test.rb
  test/integration/graphql/partners_integration_test.rb
  test/integration/graphql/site_integration_test.rb
Labels: enhancement

#1039 Tag Preselection and Datatables search fix
  app/controllers/admin/partners_controller.rb
  app/datatables/partner_datatable.rb
  app/helpers/partners_helper.rb
  app/views/admin/users/profile.html.erb
  test/integration/admin/partner_integration_test.rb
Labels: bug, patch, enhancement

#1045 Partner schema enhancement
  app/graphql/types/address_type.rb
  app/graphql/types/contact_type.rb
  app/graphql/types/neighbourhood_type.rb
  app/graphql/types/opening_hours_type.rb
  app/graphql/types/partner_type.rb
  config/routes.rb
  doc/adr/0008-partner-graphql-schema.md
  test/integration/graphql/event_integration_test.rb
  test/integration/graphql/partners_integration_test.rb
Labels: minor, enhancement

#1048 Add SitesTags. Add Site Tags to view, tests. Fix multiple select problem
  app/helpers/sites_helper.rb
  app/javascript/src/behaviors/behaviors.partner.js
  app/javascript/src/behaviors/behaviors.site.js
  app/models/site.rb
  app/models/sites_tag.rb
  app/models/tag.rb
  app/policies/site_policy.rb
  app/views/admin/partners/_form.html.erb
  app/views/admin/sites/_form.html.erb
  db/migrate/20220310125155_add_sites_tags.rb
  db/schema.rb
  test/integration/admin/partner_integration_test.rb
  test/integration/admin/sites_integration_test.rb
Labels: bug, patch

#1050 New response format for Events via graph api
  app/graphql/types/event_type.rb
  app/graphql/types/query_type.rb
  config/routes.rb
  test/integration/graphql/event_integration_test.rb
Labels: enhancement

#1059 Fix rake db:* tasks reference to production database; Add direct synchronisation task
  lib/tasks/db.rake
Labels: patch, enhancement

#1058 Add site tag filtering; add test for site tag filtering
  app/components/place_partner_preview/place_partner_preview_component.rb
  app/controllers/sites_controller.rb
  app/models/partner.rb
  app/views/admin/sites/_form.html.erb
  test/integration/partners_integration_test.rb
Labels: patch, enhancement

#1061 Fix badges + simplify some code
  app/models/event.rb
  app/models/partner.rb
  app/models/site.rb
  test/integration/partners_integration_test.rb
Labels: bug, patch

#1062 Graph api eventsByFilter endpoint
  app/graphql/types/event_queries.rb
  app/graphql/types/query_type.rb
  app/models/event.rb
  test/factories/address.rb
  test/integration/graphql/event_integration_test.rb
Labels: enhancement

#1064 GraphQL documentation
  app/graphql/types/address_type.rb
  app/graphql/types/contact_type.rb
  app/graphql/types/event_queries.rb
  app/graphql/types/event_type.rb
  app/graphql/types/neighbourhood_type.rb
  app/graphql/types/opening_hours_type.rb
  app/graphql/types/partner_type.rb
  app/graphql/types/query_type.rb
  app/graphql/types/site_type.rb
  doc/index.md
Labels: patch, docs

#1065 Improve API developer documentation
  app/graphql/types/event_type.rb
  app/graphql/types/partner_type.rb
  test/integration/graphql/partners_integration_test.rb
Labels: patch, docs

#1067 Articles can be accessed through partner API
  app/graphql/types/article_type.rb
  app/graphql/types/event_queries.rb
  app/graphql/types/event_type.rb
  app/graphql/types/partner_type.rb
  app/models/article.rb
  test/integration/graphql/event_integration_test.rb
  test/integration/graphql/partners_integration_test.rb
Labels: enhancement

#1071 GraphQL refactor
  app/graphql/types/partner_type.rb
  app/graphql/types/query_type.rb
  app/models/partner.rb
  test/integration/graphql/partners_integration_test.rb
Labels: patch, chore

#1074 Add titles to admin pages
  app/components/admin_edit/_admin_edit.html.erb
  app/components/admin_index/_admin_index.html.erb
  app/views/admin/articles/new.html.erb
  app/views/admin/calendars/new.html.erb
  app/views/admin/pages/home.html.erb
  app/views/admin/partners/edit.html.erb
  app/views/admin/partners/new.html.erb
  app/views/admin/sites/new.html.erb
  app/views/admin/tags/new.html.erb
  app/views/admin/users/new.html.erb
  app/views/layouts/_meta.html.erb
  app/views/layouts/admin/_datatable.html.erb
  app/views/layouts/admin/application.html.erb
  app/views/layouts/application.html.erb
  test/integration/admin/calendars_integration_test.rb
  test/integration/admin/home_integration_test.rb
  test/integration/admin/neighbourhood_integration_test.rb
  test/integration/admin/partner_integration_test.rb
  test/integration/admin/sites_integration_test.rb
  test/integration/admin/user_integration_test.rb
Labels: enhancement

#1078 Root user neighbourhoods bug
  app/models/partner.rb
  test/controllers/admin/partners_controller_test.rb
  test/integration/admin/partner_integration_test.rb
  test/models/partner_test.rb
  test/test_helper.rb
Labels: bug, patch

#1080 Partners can add news associated with their partners
  app/controllers/admin/articles_controller.rb
  app/datatables/article_datatable.rb
  app/helpers/articles_helper.rb
  app/javascript/src/behaviors/all_behaviors.js
  app/javascript/src/behaviors/behaviors.article.js
  app/models/article.rb
  app/models/article_partner.rb
  app/models/partner.rb
  app/policies/article_policy.rb
  app/views/admin/articles/_form.html.erb
  app/views/admin/articles/index.html.erb
  config/environments/development.rb
  test/controllers/admin/articles_controller_test.rb
  test/controllers/admin/partners_controller_test.rb
  test/factories/articles.rb
  test/factories/user.rb
  test/integration/admin/articles_integration_test.rb
  test/models/article_test.rb
  test/policies/article_policy_test.rb
Labels: enhancement

#1081 Events are filtered by site tag
  app/controllers/application_controller.rb
  app/models/event.rb
  test/integration/event_site_integration_test.rb
Labels: bug

#1084 refresh GHA cache
  .github/workflows/test.yml
Labels: chore

#1092 Find partners by tag
  app/graphql/types/query_type.rb
  test/integration/graphql/partners_integration_test.rb
Labels: enhancement

#1095 Reading articles through the GQL API
  app/graphql/types/query_type.rb
  app/models/article.rb
  test/integration/graphql/article_query_type_test.rb
Labels: enhancement

#1096 Fix papertrail causing timeouts and add rake import:nuke_papertrail
  app/models/calendar.rb
  config/initializers/paper_trail.rb
  lib/tasks/events.rake
Labels: patch, chore

#1097 Clean up postcodes with excess whitespace
  app/graphql/types/neighbourhood_type.rb
  app/models/address.rb
  app/models/neighbourhood.rb
  db/migrate/20220329140520_fix_address_and_neighbourhood_fields.rb
  db/schema.rb
  test/models/address_test.rb
  test/models/neighbourhoods_test.rb
Labels: bug

#1098 Remove event duplicates where dtstart, summary, and calendar_id are the same
  app/models/calendar.rb
  app/models/event.rb
  test/models/events_test.rb
Labels: chore
