Repository geeksforsocialchange/PlaceCal, pull requests merged in 2022-02, with the labels that each got.

#887 Improve SitesNeighbourhoods selector
  app/controllers/admin/neighbourhoods_controller.rb
  app/datatables/neighbourhood_datatable.rb
  app/helpers/sites_helper.rb
  app/javascript/packs/admin.js
  app/javascript/src/behaviors/all_behaviors.js
  app/javascript/src/behaviors/behaviors.site.js
  app/javascript/src/datatable.js
  app/models/neighbourhood.rb
  app/models/sites_neighbourhood.rb
  app/views/admin/sites/_form.html.erb
  app/views/admin/sites/_sites_neighbourhood_fields.html.erb
  db/migrate/20220125175817_add_parent_name_field_to_neighbourhoods.rb
  db/schema.rb
  package.json
  test/integration/admin/sites_integration_test.rb
  yarn.lock
Labels: minor, enhancement

#894 Partners can add and remove service areas
  README.md
  app/components/admin_edit/_admin_edit.html.erb
  app/controllers/admin/partners_controller.rb
  app/models/partner.rb
  app/policies/partner_policy.rb
  app/views/admin/partners/_form.html.erb
  app/views/layouts/admin/application.html.erb
Labels: minor, enhancement

#907 Fix some rough edges
  app/components/admin_index/_admin_index.html.erb
  app/datatables/user_datatable.rb
  app/views/admin/calendars/_form.html.erb
  app/views/admin/sites/_form.html.erb
  app/views/admin/users/profile.html.erb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/devise/unlocks/new.html.erb
  app/views/layouts/admin/_admin_topbar.html.erb
Labels: bug, patch

#910 Improve admin UI flash messages
  app/controllers/admin/calendars_controller.rb
  app/controllers/admin/collections_controller.rb
  app/controllers/admin/neighbourhoods_controller.rb
  app/controllers/admin/sites_controller.rb
  app/controllers/admin/supporters_controller.rb
  app/controllers/admin/tags_controller.rb
  app/controllers/admin/users_controller.rb
Labels: patch, enhancement

#914 Use of contextual_name in neighbourhoods selector
  app/helpers/users_helper.rb
Labels: patch, enhancement

#917 Partners hotfixes: datatable search & summary and description visibility methods
  app/datatables/partner_datatable.rb
  app/models/partner.rb
  test/models/partner_test.rb
Labels: bug, patch

#916 Removal of old v1 API
  Gemfile
  Gemfile.lock
  app/api/base.rb
  app/api/placecal/base.rb
  app/api/placecal/entities/address.rb
  app/api/placecal/entities/event.rb
  app/api/placecal/entities/partner.rb
  app/api/placecal/v1/base.rb
  app/api/placecal/v1/defaults.rb
  app/api/placecal/v1/events.rb
  config/initializers/swagger.rb
  config/routes.rb
  test/api/events_api_test.rb
Labels: minor, enhancement

#923 Base GraphQL library and mount-points
  Gemfile
  Gemfile.lock
  app/controllers/graphql_controller.rb
  app/graphql/mutations/.keep
  app/graphql/mutations/base_mutation.rb
  app/graphql/place_cal_schema.rb
  app/graphql/types/.keep
  app/graphql/types/base_argument.rb
  app/graphql/types/base_connection.rb
  app/graphql/types/base_edge.rb
  app/graphql/types/base_enum.rb
  app/graphql/types/base_field.rb
  app/graphql/types/base_input_object.rb
  app/graphql/types/base_interface.rb
  app/graphql/types/base_object.rb
  app/graphql/types/base_scalar.rb
  app/graphql/types/base_union.rb
  app/graphql/types/mutation_type.rb
  app/graphql/types/node_type.rb
  app/graphql/types/query_type.rb
  app/views/layouts/application.html.erb
  config/routes.rb
Labels: minor, enhancement

#911 Add ADR for adding accessibility info to Trans Dimension partners
  doc/adr/0007-add-accessibility-info.md
Labels: docs

#927 Graphql partner endpoints
  app/graphql/place_cal_schema.rb
  app/graphql/types/partner_type.rb
  app/graphql/types/query_type.rb
  test/integration/graphql/partners_integration_test.rb
  test/integration/graphql/ping_integration_test.rb
Labels: patch, enhancement

#934 Add events to GraphQL endpoint
  app/graphql/types/address_type.rb
  app/graphql/types/event_type.rb
  app/graphql/types/partner_type.rb
  app/graphql/types/query_type.rb
  test/integration/graphql/event_integration_test.rb
Labels: patch, enhancement

#947 Partner edit form shows related calendars and users and prompts you to add them
  Gemfile
  Gemfile.lock
  app/controllers/admin/calendars_controller.rb
  app/controllers/admin/users_controller.rb
  app/helpers/calendars_helper.rb
  app/views/admin/calendars/_form.html.erb
  app/views/admin/partners/_form.html.erb
  app/views/admin/partners/edit.html.erb
  app/views/admin/partners/new.html.erb
  app/views/admin/users/_form.html.erb
  test/integration/admin/calendars_integration_test.rb
  test/integration/admin/partner_integration_test.rb
  test/integration/admin/user_integration_test.rb
Labels: patch, enhancement

#951 Admin users must confirm user delete
  app/views/admin/users/edit.html.erb
Labels: patch, enhancement

#950 Tweak Invite User email text
  config/locales/devise_invitable.en.yml
Labels: enhancement

#967 Remove partner summary truncation
  app/components/place_partner_preview/_place_partner_preview.html.erb
Labels: patch, enhancement

#968 Show service area information on location lozenges
  app/assets/stylesheets/base/turf.sass
  app/components/place_partner_preview/_place_partner_preview.html.erb
  app/components/place_partner_preview/place_partner_preview_component.rb
  app/helpers/partners_helper.rb
  app/models/partner.rb
  app/views/admin/users/profile.html.erb
  app/views/partners/index.html.erb
  app/views/partners/show.html.erb
  test/helpers/partners_helper_test.rb
  test/integration/admin/user_integration_test.rb
  test/integration/partners_integration_test.rb
Labels: patch, enhancement

#996 Graphql sites API endpoints
  app/graphql/types/neighbourhood_type.rb
  app/graphql/types/query_type.rb
  app/graphql/types/site_type.rb
  test/integration/graphql/site_integration_test.rb
Labels: patch, enhancement
