Repository geeksforsocialchange/PlaceCal, pull requests merged in 2022-05, with the labels that each got.

#1199 Filtering partners with addresses
  app/helpers/calendars_helper.rb
  app/models/partner.rb
  test/helpers/calendars_helper_test.rb
Labels: bug

#1197 Calendars can be imported from the admin UI
  app/controllers/admin/calendars_controller.rb
  test/controllers/admin/calendars_controller_test.rb
Labels: bug

#1204 Assign partners to events when imported
  app/components/place_partner_preview/place_partner_preview_component.rb
  app/controllers/events_controller.rb
  app/graphql/types/event_queries.rb
  app/jobs/calendar_importer/event_resolver.rb
  app/jobs/calendar_importer/parsers/base.rb
  app/jobs/calendar_importer/parsers/ics.rb
  app/models/event.rb
  app/views/admin/partners/edit.html.erb
  app/views/partners/index.html.erb
  test/factories/event.rb
  test/models/events_test.rb
Labels: bug, patch

#1206 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: chore

#1212 Remove buggy JS on calendar strategy selector
  app/javascript/src/calendar-form.js
Labels: bug

#1218 Make Calendar code slightly clearer
  app/jobs/calendar_importer/event_resolver.rb
  app/models/address.rb
  lib/tasks/events.rake
Labels: chore

#1222 Passthrough 'event' strategy if no location
  app/jobs/calendar_importer/event_resolver.rb
  app/models/event.rb
Labels: enhancement

#1223 Add a "no location" strategy to Calendars
  app/helpers/calendars_helper.rb
  app/jobs/calendar_importer/event_resolver.rb
  app/models/calendar.rb
  app/models/event.rb
  test/controllers/events_controller_test.rb
  test/controllers/partners_controller_test.rb
  test/jobs/calendar_importer/event_resolver_test.rb
Labels: bug

#1225 Calendar notice count
  app/jobs/calendar_importer_job.rb
  app/models/calendar.rb
  test/models/calendar_test.rb
Labels: bug

#1227 Update depends
  Gemfile.lock
  package.json
  yarn.lock
Labels: chore

#1231 Remove DATE() from find_by_day
  app/controllers/application_controller.rb
  app/models/event.rb
  test/models/events_test.rb
Labels: bug

#1232 Sanitise and combine strings on iCal event description fields
  app/jobs/calendar_importer/calendar_importer_task.rb
  app/jobs/calendar_importer/events/base.rb
  app/jobs/calendar_importer/events/ics_event.rb
  lib/tasks/events.rake
Labels: bug

#1235 'Invite new partner admin' preselection doesn't stick
  app/policies/user_policy.rb
  test/controllers/admin/users_controller_test.rb
Labels: bug, patch

#1236 Stop semrushbot/ahrefsbot/bing spam after calendar reimport
  config/robots/robots.production.txt
Labels: chore

#1237 Migrate to delayed_job and add ActiveJob worker
  Procfile.dev
  app/controllers/admin/jobs_controller.rb
  app/views/admin/jobs/index.html.erb
  app/views/layouts/admin/_admin_navigation.html.erb
  config/routes.rb
  lib/tasks/events.rake
Labels: enhancement

#1241 Add Procfile
  DOKKU_SCALE
  Procfile
Labels: enhancement

#1242 Add cronjob for production environments
  app.json
Labels: enhancement

#1245 Improve feedback on calendar importer process
  .gitignore
  app/controllers/admin/calendars_controller.rb
  app/controllers/admin/jobs_controller.rb
  app/datatables/calendar_datatable.rb
  app/helpers/calendars_helper.rb
  app/jobs/calendar_importer/calendar_importer_task.rb
  app/jobs/calendar_importer_job.rb
  app/models/calendar.rb
  app/models/events/base.rb
  app/models/events/eventbrite_event.rb
  app/models/events/facebook_event.rb
  app/models/events/ics_event.rb
  app/models/events/manchester_uni_event.rb
  app/models/events/meetup_event.rb
  app/models/events/zarts_event.rb
  app/views/admin/calendars/_import.html.erb
  app/views/admin/calendars/_status.html.erb
  app/views/admin/calendars/index.html.erb
  app/views/admin/calendars/show.html.erb
  app/views/admin/jobs/index.html.erb
  app/views/admin/pages/home.html.erb
  app/views/layouts/admin/_admin_navigation.html.erb
  db/migrate/20220510134827_add_state_to_calendar.rb
  db/schema.rb
  lib/tasks/events.rake
  test/models/calendar_state_test.rb
Labels: enhancement

#1251 1238 - Add OnlineAddress and online_only import strategy
  app/helpers/calendars_helper.rb
  app/jobs/calendar_importer/calendar_importer_task.rb
  app/jobs/calendar_importer/event_resolver.rb
  app/models/calendar.rb
  app/models/event.rb
  app/models/online_address.rb
  app/models/tag.rb
  app/views/admin/calendars/_status.html.erb
  config/initializers/delayed_job_config.rb
  db/migrate/20220512144807_create_online_addresses.rb
  db/schema.rb
  lib/tasks/workers.rake
  test/factories/online_addresses.rb
  test/helpers/calendars_helper_test.rb
  test/jobs/calendar_importer/event_resolver_test.rb
  test/models/address_test.rb
  test/models/online_address_test.rb
Labels: enhancement

#1252 Manual importer selection
  app/helpers/calendars_helper.rb
  app/jobs/calendar_importer/calendar_importer.rb
  app/jobs/calendar_importer/calendar_importer_task.rb
  app/jobs/calendar_importer/parsers/base.rb
  app/jobs/calendar_importer/parsers/eventbrite.rb
  app/jobs/calendar_importer/parsers/facebook.rb
  app/jobs/calendar_importer/parsers/ics.rb
  app/jobs/calendar_importer/parsers/meetup.rb
  app/jobs/calendar_importer/parsers/ticketsolve.rb
  app/models/calendar.rb
  app/views/admin/calendars/_form.html.erb
  db/migrate/20220516083725_add_importer_mode_to_calendar.rb
  db/schema.rb
  test/fixtures/vcr_cassettes/Uknown_Teamup_Feed.yml
  test/jobs/calendar_importer/calendar_importer_task_test.rb
  test/jobs/calendar_importer/calendar_importer_test.rb
  test/models/calendar_state_test.rb
Labels: enhancement

#1253 Saving calendar import mode on admin page
  app/controllers/admin/calendars_controller.rb
  test/integration/admin/calendars_integration_test.rb
Labels: bug, chore

#1255 Bug: Events should not set their own address
  app/jobs/calendar_importer/event_resolver.rb
  app/models/address.rb
  app/models/event.rb
  test/jobs/calendar_importer/event_resolver_strategy_test.rb
Labels: bug, patch

#1258 Fix importer bug where event changes are not saved
  app/jobs/calendar_importer/calendar_importer_task.rb
  app/jobs/calendar_importer/event_resolver.rb
Labels: bug, patch

#1263 Map not showing bug
  .env.example
  Procfile.dev
  app/assets/stylesheets/base/map.sass
  app/assets/stylesheets/globals.sass
  app/components/map/_map.html.erb
  app/components/map/map.yml
  app/components/map/map_component.rb
  app/components/navigation/_navigation.html.erb
  app/helpers/map_helper.rb
  app/javascript/application.js
  app/javascript/src/map_handler.js
  app/views/events/show.html.erb
  app/views/layouts/application.html.erb
  app/views/partners/index.html.erb
  app/views/partners/show.html.erb
  app/views/shared/_map.html.erb
  app/views/shared/_map_configuration.html.erb
  app/views/shared/_map_reset.html.erb
  test/integration/event_integration_test.rb
Labels: bug, patch

#1267 Fix bug where users were unable to edit a partner without a common ward
  app/models/partner.rb
  test/controllers/admin/partners_controller_test.rb
  test/controllers/partners_controller_test.rb
  test/factories/event.rb
Labels: bug, patch
