Repository geeksforsocialchange/PlaceCal, pull requests merged in 2022-10, with the labels that each got.

#1485 Inherit default route options for ActionMailer from routes
  config/environments/development.rb
  config/environments/production.rb
  config/environments/staging.rb
  config/environments/test.rb
  test/system/create_admin_users_test.rb
Labels: bug, ruby, urgent

#1468 Document how to make a release
  RELEASING.md
Labels: docs

#1473 Upload test screenshots on failure
  .github/workflows/test.yml
Labels: tech debt, chore

#1499 Update link to PlaceCal handbook on calendar admin page
  app/views/admin/calendars/_form.html.erb
Labels: bug

#1492 Fix: make importer JSON parsing more robust
  app/jobs/calendar_importer/parsers/base.rb
  app/jobs/calendar_importer/parsers/meetup.rb
  test/fixtures/vcr_cassettes/bad_meetup_gateway.yml
  test/jobs/calendar_importer/meetup_parser_test.rb
  test/jobs/calendar_importer/parser_base_test.rb
Labels: bug, patch

#1494 Fix: Don't try to hash non string inputs
  app/jobs/calendar_importer/parsers/ics.rb
Labels: bug, patch

#1495 Fix: Address lookup failure recovery
  .rubocop_todo.yml
  app/models/address.rb
Labels: bug, patch

#1496 Feature: Not Found page
  app/assets/stylesheets/globals.sass
  app/assets/stylesheets/home.sass
  app/assets/stylesheets/home/pages/_resource_not_found.sass
  app/controllers/application_controller.rb
  app/views/pages/resource_not_found.html.erb
  test/integration/event_integration_test.rb
Labels: enhancement

#1488 Use uk_postcode gem for postcode validation
  Gemfile
  Gemfile.lock
  app/jobs/calendar_importer/events/base.rb
  app/models/address.rb
  app/validators/postcode_validator.rb
  test/models/address_test.rb
Labels: bug, patch, impacts client

#1501 Fix: better calendar feedback when import fails
  app/jobs/calendar_importer/parsers/base.rb
  app/jobs/calendar_importer/parsers/ics.rb
  app/jobs/calendar_importer_job.rb
  test/fixtures/vcr_cassettes/Importer_ICS_Bad_Response.yml
  test/jobs/calendar_importer/event_parse_ics_test.rb
Labels: bug, patch

#1505 Drop Guard
  .rubocop_todo.yml
  Gemfile
  Gemfile.lock
  Guardfile
Labels: tech debt, chore

#1506 Improve issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/technical_debt.md
Labels: chore

#1507 Use chore over tech debt for issue labelling
  .github/ISSUE_TEMPLATE/technical_debt.md
Labels: patch, chore

#1508 Improve the GitHub Actions
  .github/workflows/deploy-to-production.yml
  .github/workflows/deploy-to-staging.yml
  .github/workflows/issue-label-assign.yml
  .github/workflows/test.yml
Labels: chore

#1513 Fix deployment actions
  .github/workflows/deploy-to-production.yml
  .github/workflows/deploy-to-staging.yml
  .github/workflows/release-drafter.yml
  .github/workflows/test.yml
  bin/test
Labels: chore

#1503 Support ld+json website feeds starting with OutSavvy
  .rubocop_todo.yml
  Gemfile
  Gemfile.lock
  app/components/paginator/paginator_component.rb
  app/jobs/calendar_importer/calendar_importer.rb
  app/jobs/calendar_importer/events/out_savvy_event.rb
  app/jobs/calendar_importer/parsers/out_savvy.rb
  config/database.yml
  config/routes.rb
  db/data/20180625172033_add_sites.rb
  db/migrate/20180625172806_add_supporter_data.rb
  test/fixtures/vcr_cassettes/out_savvy_events.yml
  test/jobs/calendar_importer/calendar_importer_task_test.rb
  test/jobs/calendar_importer/out_savvy_event_parser_test.rb
Labels: enhancement

#1516 Attempt to fix deploy to staging workflow
  .github/workflows/deploy-to-staging.yml
Labels: chore

#1517 Put workflow name back how it was
  .github/workflows/deploy-to-staging.yml
Labels: chore

#1518 Checkout the repo before attempting to deploy it
  .github/workflows/deploy-to-production.yml
  .github/workflows/deploy-to-staging.yml
Labels: chore
