Repository geeksforsocialchange/PlaceCal, pull requests merged in 2022-08, with the labels that each got.

#1409 Refactor select2 javascript using Stimulus and add system tests for select2 inputs
  .github/workflows/test.yml
  Gemfile
  Gemfile.lock
  app/javascript/admin.js
  app/javascript/controllers/application.js
  app/javascript/controllers/index.js
  app/javascript/controllers/select2_controller.js
  app/javascript/src/behaviors/all_behaviors.js
  app/javascript/src/behaviors/behaviors.article.js
  app/javascript/src/behaviors/behaviors.calendar.js
  app/javascript/src/behaviors/behaviors.neighbourhood.js
  app/javascript/src/behaviors/behaviors.partner.js
  app/javascript/src/behaviors/behaviors.site.js
  app/javascript/src/behaviors/behaviors.tag.js
  app/javascript/src/behaviors/behaviors.user.js
  app/views/admin/articles/_form.html.erb
  app/views/admin/calendars/_form.html.erb
  app/views/admin/neighbourhoods/_form.html.erb
  app/views/admin/partners/_form.html.erb
  app/views/admin/partners/_service_area_fields.html.erb
  app/views/admin/sites/_form.html.erb
  app/views/admin/sites/_sites_neighbourhood_fields.html.erb
  app/views/admin/tags/_form.html.erb
  app/views/admin/users/_form.html.erb
  test/system/admin/article_test.rb
  test/system/admin/calendar_test.rb
  test/system/admin/neighbourhood_test.rb
  test/system/admin/partner_test.rb
  test/system/admin/site_test.rb
  test/system/admin/tag_test.rb
  test/system/admin/user_test.rb
  test/test_helper.rb
Labels: patch, enhancement

#1426 Refactor conditional rendering for primary neighbourhood in site admin
  app/javascript/src/behaviors/all_behaviors.js
  app/javascript/src/behaviors/behaviors.site.js
  app/views/admin/sites/_sites_neighbourhood_fields.html.erb
  test/system/admin/site_test.rb
Labels: patch, chore

#1430 Refactor leaflet map loading with stimulus controller
  app/javascript/application.js
  app/javascript/controllers/index.js
  app/javascript/controllers/leaflet_controller.js
  app/javascript/src/map_handler.js
  app/views/admin/partners/_form.html.erb
  app/views/layouts/application.html.erb
  app/views/shared/_map.html.erb
  app/views/shared/_map_configuration.html.erb
  app/views/shared/_map_reset.html.erb
  test/integration/event_integration_test.rb
Labels: patch, chore

#1424 Refactor image preview on upload field in partner admin in stimulus
  app/javascript/controllers/image_preview_controller.js
  app/javascript/controllers/index.js
  app/javascript/src/behaviors/behaviors.partner.js
  app/views/admin/partners/_form.html.erb
  test/system/admin/damir-omerovic-UMaGtammiSI-unsplash.jpg
  test/system/admin/partner_test.rb
Labels: patch, chore

#1406 Improve README
  .env.example
  README.md
Labels: enhancement

#1432 Fix duplicate partners on partner index pages
  app/models/partner.rb
  test/integration/partners_integration_test.rb
  test/models/partner_site_scope_test.rb
Labels: bug, patch

#1438 Revert "Fix duplicate partners on partner index pages (#1432)"
  app/models/partner.rb
  test/integration/partners_integration_test.rb
  test/models/partner_site_scope_test.rb
Labels: bug, patch

#1439 Fix site partner filter
  app/models/neighbourhood.rb
  app/models/partner.rb
  test/factories/neighbourhood.rb
  test/factories/partner.rb
  test/integration/partners_integration_test.rb
  test/models/partner_site_scope_test.rb
  test/support/geocoder.rb
  test/test_helper.rb
Labels: bug, patch

#1434 Refactor opening times picker with stimulus controller
  app/javascript/admin.js
  app/javascript/controllers/index.js
  app/javascript/controllers/opening_times_controller.js
  app/javascript/src/opening-times.js
  app/views/admin/partners/_form.html.erb
  app/views/admin/partners/_opening_times.html.erb
  package.json
  test/system/admin/partner_test.rb
  yarn.lock
Labels: patch, chore
