Repository geeksforsocialchange/PlaceCal, pull requests merged in 2022-07, with the labels that each got.

#1368 fix: Root users incorrectly getting warning they have no rights
  app/helpers/users_helper.rb
  test/integration/admin/home_integration_test.rb
Labels: bug, patch

#1385 Partners with service areas appear on maps
  app/controllers/application_controller.rb
  app/controllers/collections_controller.rb
  app/controllers/concerns/map_markers.rb
  app/controllers/events_controller.rb
  app/controllers/partners_controller.rb
  test/controllers/concerns/map_markers_concern_test.rb
Labels: enhancement

#1382 Remove legacy Facebook integration code
  Gemfile
  Gemfile.lock
  app/components/contact_details/_contact_details.html.erb
  app/controllers/admin/calendars_controller.rb
  app/controllers/admin/omniauth_callbacks_controller.rb
  app/controllers/admin/users_controller.rb
  app/graphql/types/partner_type.rb
  app/jobs/calendar_importer/calendar_importer.rb
  app/jobs/calendar_importer/events/facebook_event.rb
  app/jobs/calendar_importer/events/ics_event.rb
  app/jobs/calendar_importer/parsers/facebook.rb
  app/models/calendar.rb
  app/models/user.rb
  app/policies/partner_policy.rb
  app/policies/user_policy.rb
  app/views/admin/calendars/_form.html.erb
  app/views/admin/calendars/index.html.erb
  app/views/admin/calendars/select_page.html.erb
  app/views/admin/users/_form.html.erb
  app/views/admin/users/profile.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/partners/show.html.erb
  config/initializers/filter_parameter_logging.rb
  config/initializers/omniauth.rb
  config/locales/en.yml
  config/routes.rb
  config/secrets.yml
  db/migrate/20220711161804_remove_facebook_fields.rb
  db/schema.rb
  test/factories/partner.rb
  test/integration/admin/partner_integration_test.rb
  test/integration/admin/user_integration_test.rb
  test/integration/graphql/partners_integration_test.rb
  test/jobs/calendar_importer/calendar_importer_test.rb
  test/jobs/calendar_importer/event_resolver_test.rb
Labels: chore

#1395 Simplify and clarify calendar contact form information
  app/controllers/admin/calendars_controller.rb
  app/views/admin/calendars/_form.html.erb
  db/migrate/20220720151156_remove_calendar_contact_info_fields.rb
  db/schema.rb
  test/factories/calendar.rb
Labels: enhancement

#1398 Bump of version of rails (for activerecord)
  Gemfile
  Gemfile.lock
Labels: chore

#1399 Urls on find-my-placecal page go to the correct domain
  app/views/pages/find_placecal.html.erb
  test/integration/sites_integration_test.rb
Labels: bug

#1400 Fix calendar importer tasks stuck in "in worker" mode
  app/models/calendar.rb
  test/models/calendar_state_test.rb
Labels: bug, patch

#1401 Site admin contact selector has a search filter
  app/views/admin/sites/_form.html.erb
Labels: bug, patch, enhancement

#1403 Make multi-day events show properly in interface (#1214)
  app/components/event/event_component.rb
  app/models/event.rb
  test/controllers/events_controller_test.rb
  test/integration/event_site_integration_test.rb
  test/models/events_test.rb
Labels: enhancement
