Repository geeksforsocialchange/PlaceCal, pull requests merged in 2022-09, with the labels that each got.

#1442 Remove Vue as dependency (1417)
  app/inputs/vue_string_input.rb
  app/javascript/admin.js
  app/javascript/src/calendar-form.js
  app/javascript/src/ward-picker.js
  config/webpack/loaders/vue.js
  esbuild.config.js
  package.json
  yarn.lock
Labels: chore

#1447 Document Graphviz dependency
  README.md
Labels: docs

#1446 Support nodenv
  .node-version
  .nvmrc
  README.md
Labels: chore

#1451 Fix: scoping on site partners by tag
  app/components/computer_access/_computer_access.html.erb
  app/components/free_public_wifi/_free_public_wifi.html.erb
  app/controllers/sites_controller.rb
  app/models/partner.rb
  test/integration/sites_integration_test.rb
  test/models/partner_site_with_tag_scope_test.rb
Labels: bug, patch

#1458 Chore: tests covering image upload problems
  app/components/error/_error.html.erb
  app/controllers/admin/sites_controller.rb
  app/views/admin/users/_form.html.erb
  test/fixtures/files/bad-cat-picture.bmp
  test/integration/admin/articles_integration_test.rb
  test/integration/admin/partner_integration_test.rb
  test/integration/admin/sites_integration_test.rb
  test/integration/admin/user_integration_test.rb
Labels: patch, chore

#1459 Automate setup
  .env.example
  README.md
  bin/setup
  bin/update
  bin/yarn
Labels: tech-debt, chore

#1465 Fix: set up domain and build partner logo url
  .env.example
  app/graphql/types/partner_type.rb
  app/models/partner.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/staging.rb
  config/environments/test.rb
Labels: bug, patch

#1461 Fix: partner tag selector bug
  app/models/partner.rb
  app/views/admin/partners/_opening_times.html.erb
  test/models/partner_test.rb
  test/system/admin/partner_test.rb
  test/test_helper.rb
Labels: bug, patch
