Repository geeksforsocialchange/PlaceCal, pull requests merged in 2022-06, with the labels that each got.

#1270 Importer not logging importer used
  app/jobs/calendar_importer/calendar_importer_task.rb
  app/jobs/calendar_importer/event_resolver.rb
  app/jobs/calendar_importer/parsers/ics.rb
  app/jobs/calendar_importer_job.rb
  app/models/calendar.rb
  lib/tasks/events.rake
Labels: bug

#1273 Change contact letters with icons
  app/assets/images/icons/email.svg
  app/assets/images/icons/facebook.svg
  app/assets/images/icons/phone.svg
  app/assets/images/icons/twitter.svg
  app/assets/images/icons/website.svg
  app/assets/stylesheets/base/icons.sass
  app/components/contact_details/_contact_details.html.erb
  db/schema.rb
Labels: enhancement

#1274 Allow tags to be set as uneditable
  app/datatables/tag_datatable.rb
  app/models/tag.rb
  app/policies/tag_policy.rb
  app/views/admin/tags/_form.html.erb
  app/views/admin/tags/edit.html.erb
  app/views/admin/tags/index.html.erb
  db/migrate/20220607161025_add_system_flag_to_tags.rb
  db/schema.rb
  test/factories/tag.rb
  test/integration/admin/tags_integration_test.rb
  test/models/tag_test.rb
  test/policies/tag_policy_test.rb
Labels: enhancement

#1275 Add column titles to datatables
  app/views/admin/articles/index.html.erb
  app/views/admin/calendars/index.html.erb
  app/views/admin/collections/index.html.erb
  app/views/admin/neighbourhoods/index.html.erb
  app/views/admin/partners/index.html.erb
  app/views/admin/sites/index.html.erb
  app/views/admin/supporters/index.html.erb
  app/views/admin/tags/index.html.erb
  app/views/admin/users/index.html.erb
  app/views/layouts/admin/_datatable.html.erb
Labels: enhancement

#1278 Update rails and rack
  Gemfile
  Gemfile.lock
Labels: chore

#1280 Site tag cards
  app/assets/stylesheets/base/grid.sass
  app/components/computer_access/_computer_access.erb
  app/components/computer_access/_computer_access.html.erb
  app/components/free_public_wifi/_free_public_wifi.html.erb
  app/controllers/sites_controller.rb
  app/models/partner.rb
  app/views/sites/default.html.erb
  test/integration/sites_integration_test.rb
Labels: enhancement

#1281 fix: temp fix for workflow fail due to external bug
  .github/workflows/test.yml
Labels: bug, patch

#1268 Make online address visible in PlaceCal/GraphQL
  app/components/event/event_component.rb
  app/graphql/types/event_type.rb
  app/helpers/events_helper.rb
  app/jobs/calendar_importer/calendar_importer.rb
  app/jobs/calendar_importer/event_resolver.rb
  app/jobs/calendar_importer/events/eventbrite_event.rb
  app/jobs/calendar_importer/events/ics_event.rb
  app/jobs/calendar_importer/events/meetup_event.rb
  app/jobs/calendar_importer_job.rb
  app/models/online_address.rb
  app/views/events/show.html.erb
  db/migrate/20220524160826_add_link_type_to_online_address.rb
  db/schema.rb
  lib/tasks/events.rake
  test/integration/graphql/event_integration_test.rb
Labels: enhancement

#1289 fix: use email rather than name when displaying partners users
  app/views/admin/partners/edit.html.erb
Labels: bug, patch

#1291 Remove HTML from imported events
  app/helpers/application_helper.rb
  app/jobs/calendar_importer/events/base.rb
  app/models/article.rb
  app/models/concerns/html_render_cache.rb
  app/models/event.rb
  app/models/partner.rb
  app/models/site.rb
  app/views/events/show.html.erb
  app/views/news/index.html.erb
  app/views/news/show.html.erb
  app/views/partners/show.html.erb
  app/views/sites/default.html.erb
  app/views/sites/mossley.html.erb
  db/migrate/20220611154511_add_html_fields_to_models.rb
  db/schema.rb
  lib/tasks/data.rake
  test/jobs/calendar_importer/event_base_html_sanitize_test.rb
  test/models/article_test.rb
Labels: bug, patch

#1297 Improve invite email
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/email_changed.html.erb
  app/views/devise/mailer/invitation_instructions.html.erb
  app/views/devise/mailer/invitation_instructions.text.erb
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/unlock_instructions.html.erb
Labels: enhancement

#1302 Fix data migration
  lib/tasks/data.rake
Labels: bug, patch

#1305 Another fix for rake task that populates historical html
  lib/tasks/data.rake
Labels: bug, patch

#1312 Improve event display when there are limited events
  app/components/paginator/_paginator.html.erb
  app/components/paginator/paginator_component.rb
  app/controllers/partners_controller.rb
  app/views/partners/show.html.erb
  db/schema.rb
  test/integration/partner_integration_test.rb
Labels: enhancement

#1313 Reset password form bug
  app/components/admin_flash/admin_flash.sass
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  config/environments/development.rb
Labels: bug, patch

#1315 bug: root domain flash styling fix
  app/assets/stylesheets/base/flash.sass
  app/assets/stylesheets/globals.sass
Labels: bug, patch

#1323 Fix accept invitation form and redirect
  app/controllers/users/invitations_controller.rb
  app/views/devise/invitations/edit.html.erb
Labels: bug, patch

#1326 Only show certain nav links to certain admins
  app/helpers/application_helper.rb
  app/views/layouts/admin/_admin_navigation.html.erb
Labels: bug

#1325 News items bugs
  app/assets/stylesheets/articles/_index.sass
  app/assets/stylesheets/articles/_show.sass
  app/controllers/application_controller.rb
  app/helpers/articles_helper.rb
  app/models/article.rb
  app/views/news/index.html.erb
  app/views/news/show.html.erb
  test/integration/news_integration_test.rb
Labels: enhancement

#1331 Show article page layout and styling
  app/assets/stylesheets/articles/_index.sass
  app/assets/stylesheets/articles/_show.sass
  app/views/news/show.html.erb
Labels: enhancement

#1336 fix: redirect to find my placecal on main site
  app/controllers/application_controller.rb
  app/controllers/events_controller.rb
  app/controllers/news_controller.rb
  app/controllers/partners_controller.rb
  config/routes.rb
  test/controllers/events_controller_test.rb
  test/controllers/partners_controller_test.rb
  test/integration/event_integration_test.rb
  test/integration/events_integration_test.rb
  test/integration/partner_integration_test.rb
  test/integration/partners_integration_test.rb
  test/test_helper.rb
Labels: bug, patch

#1349 Change of text on admin edit partner page.
  .gitignore
  app/views/admin/partners/edit.html.erb
Labels: enhancement

#1354 Text and formatting change
  app/views/joins/new.html.erb
Labels: enhancement

#1363 Guards against badly formed JSON in Partners
  app/models/partner.rb
  test/models/partner_test.rb
Labels: bug

#1364 No rights for user message on admin dashboard
  app/views/admin/pages/home.html.erb
  test/integration/admin/home_integration_test.rb
Labels: enhancement
