Repository geeksforsocialchange/PlaceCal, pull requests merged in 2023-02, with the labels that each got.

#1677 Fix eventbrite calendar parser raising a "bad gateway" error
  app/jobs/calendar_importer/parsers/eventbrite.rb
  test/fixtures/vcr_cassettes/eventbrite_bad_gateway.yml
  test/jobs/calendar_importer/eventbrite_parser_test.rb
Labels: bug, e

#1684 Add type column to tags table
  db/migrate/20230214120329_add_type_to_tag_table.rb
  db/schema.rb
Labels: enhancement

#1689 Admin tag type visibility
  app/controllers/admin/tags_controller.rb
  app/models/facility.rb
  app/policies/facility_policy.rb
  app/policies/tag_policy.rb
  app/views/admin/tags/_form.html.erb
  app/views/admin/tags/index.html.erb
  test/integration/admin/tags_integration_test.rb
  test/policies/tag_policy_test.rb
  test/system/admin/tag_test.rb
Labels: enhancement

#1693 Add category tags and script to seed them
  app/models/category.rb
  app/models/tag.rb
  app/policies/category_policy.rb
  app/views/admin/tags/_form.html.erb
  lib/tasks/placecal.rake
Labels: enhancement

#1696 Tag filter for admin tags index page
  app/controllers/admin/tags_controller.rb
  app/controllers/concerns/tag_filter.rb
  app/views/admin/tags/index.html.erb
  test/controllers/concerns/tag_filter_test.rb
Labels: enhancement

#1701 Remove News link, rehome admin Articles nav
  app/controllers/application_controller.rb
  app/views/layouts/admin/_admin_navigation.html.erb
  test/integration/news_integration_test.rb
Labels: enhancement

#1700 Make rg search respect gitignore
  .gitignore
Labels: chore

#1704 Make Tag type visible on Partner edit page
  app/helpers/partners_helper.rb
  app/models/tag.rb
  app/views/admin/partners/_form.html.erb
  test/integration/admin/partner_integration_test.rb
  test/system/admin/partner_test.rb
Labels: enhancement

#1709 Remove tag "edit permission" field
  app/datatables/tag_datatable.rb
  app/helpers/tags_helper.rb
  app/models/tag.rb
  app/policies/tag_policy.rb
  app/views/admin/tags/_form.html.erb
  db/migrate/20230223154845_drop_tag_edit_permissions_field.rb
  db/schema.rb
  test/controllers/admin/tags_controller_test.rb
  test/factories/tag.rb
  test/system/admin/article_test.rb
  test/system/admin/partner_test.rb
  test/system/admin/site_test.rb
  test/system/admin/tag_test.rb
  test/system/admin/user_test.rb
Labels: enhancement

#1706 Validate Address postcodes
  app/models/address.rb
  app/models/neighbourhood.rb
  app/views/admin/partners/edit.html.erb
  test/models/address_test.rb
  test/support/geocoder.rb
Labels: enhancement

#1714 Hide Tag "Assigned Users" field unless it's a Partnership
  app/helpers/tags_helper.rb
  app/views/admin/tags/_form.html.erb
  test/integration/admin/tags_integration_test.rb
Labels: v, e, enhancement, impacts client
